import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@rtrw-monitoring-system/provider";
import { Suspense } from "react";
import Image from "next/image";
import ICONS from "@rtrw-monitoring-system/public/assets/icons";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Welcome to RT/RW Monitoring System",
  description: "Generated by Telkomsel",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Suspense
            fallback={
              <div className="flex h-screen w-screen items-center justify-center bg-white">
                <Image
                  src={ICONS.TelkomselLogo}
                  alt="telkomsel-logo"
                  width={279}
                  height={91}
                />
              </div>
            }
          >
            {children}
          </Suspense>
        </Providers>
      </body>
    </html>
  );
}
