import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Providers from "@rtrw-monitoring-system/provider";
import { Suspense } from "react";
import Image from "next/image";
import ICONS from "@rtrw-monitoring-system/public/assets/icons";
import useInitialOneSignal from "libs/hooks/useOneSignal";

const montserratFont = Montserrat({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-montserrat",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Welcome to RT/RW Monitoring System",
  description: "Generated by Telkomsel",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // useInitialOneSignal();

  return (
    <html lang="en" className={montserratFont.variable}>
      <body>
        <Providers>
          <Suspense
            fallback={
              <div className="flex h-screen w-screen items-center justify-center bg-white">
                <Image
                  src={ICONS.TelkomselLogo}
                  alt="telkomsel-logo"
                  width={279}
                  height={91}
                />
              </div>
            }
          >
            {children}
          </Suspense>
        </Providers>
      </body>
    </html>
  );
}
